# .github/workflows/deploy.yml
name: Streamlit Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint Check
        run: |
          flake8 .

      - name: Run Streamlit (test only)
        run: |
          streamlit run main.py --server.headless true &
          sleep 10
