name: Test Python Setup

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Print Python Version
        run: python --version

      - name: Install Dependencies
        run: |
            pip install -r requirements.txt

      - name: Run Streamlit (test only)
        run: |
            streamlit run code/dashboard.py --server.headless true &
            sleep 10
    